@server = http://localhost
@port = 3000
@resource =
@url = {{server}}:{{port}}/{{resource}}

###############################################

// Test: Get blablabla
// Expected HTTP response status code: 200
// Expected response: an object (json) with an array with all courses (including subject for each course)
// [{}, {}, ...]
GET {{url}}testing

